// Generated by scripts/generate-swift-bindings.sh (scripts/check-swift-mirror.py).
// Do not edit. One field-for-field conversion per product type, in each
// direction, between the generated binding (YadoriLinkFFI) and the app's
// mirror types (YadoriLinkModel).

import Foundation
import YadoriLinkFFI
import YadoriLinkModel

extension YadoriLinkModel.AcceptInviteOutcome {
    init(_ value: YadoriLinkFFI.AcceptInviteOutcome) {
        self.init(groupId: value.groupId, localPath: value.localPath, awaitingApproval: value.awaitingApproval)
    }
}

extension YadoriLinkModel.AccountDeletionRequest {
    init(_ value: YadoriLinkFFI.AccountDeletionRequest) {
        self.init(confirmationToken: value.confirmationToken)
    }
}

extension YadoriLinkModel.AccountDeletionState {
    init(_ value: YadoriLinkFFI.AccountDeletionState) {
        switch value {
        case .active: self = .active
        case .requested: self = .requested
        case .grace: self = .grace
        case let .other(raw): self = .other(raw: raw)
        }
    }
}

extension YadoriLinkModel.AccountDeletionStatus {
    init(_ value: YadoriLinkFFI.AccountDeletionStatus) {
        self.init(state: YadoriLinkModel.AccountDeletionState(value.state), graceExpiresAt: value.graceExpiresAt, remaining: value.remaining)
    }
}

extension YadoriLinkModel.AccountStatus {
    init(_ value: YadoriLinkFFI.AccountStatus) {
        self.init(signIn: YadoriLinkModel.SignInState(value.signIn), clientId: value.clientId, thisDeviceId: value.thisDeviceId, deviceRegistered: value.deviceRegistered, defaultDeviceName: value.defaultDeviceName, hasLinkedFolders: value.hasLinkedFolders)
    }
}

extension YadoriLinkModel.ApproveOutcome {
    init(_ value: YadoriLinkFFI.ApproveOutcome) {
        switch value {
        case .approved: self = .approved
        case .alreadyActive: self = .alreadyActive
        case let .unrecognized(raw): self = .unrecognized(raw: raw)
        }
    }
}

extension YadoriLinkModel.AssignableRole {
    init(_ value: YadoriLinkFFI.AssignableRole) {
        switch value {
        case .viewer: self = .viewer
        case .editor: self = .editor
        }
    }
}

extension YadoriLinkModel.AttentionCategory {
    init(_ value: YadoriLinkFFI.AttentionCategory) {
        switch value {
        case .degraded: self = .degraded
        case .durabilityAtRisk: self = .durabilityAtRisk
        case .durabilityUnknown: self = .durabilityUnknown
        case .fetchUnavailable: self = .fetchUnavailable
        case .fetchAvailabilityUnknown: self = .fetchAvailabilityUnknown
        case .conflict: self = .conflict
        case .held: self = .held
        case .lowDiskCritical: self = .lowDiskCritical
        case .lowDisk: self = .lowDisk
        case .peerDisconnected: self = .peerDisconnected
        case .recentError: self = .recentError
        case .updateFailed: self = .updateFailed
        case .unrecognized: self = .unrecognized
        }
    }
}

extension YadoriLinkModel.AttentionReason {
    init(_ value: YadoriLinkFFI.AttentionReason) {
        self.init(category: YadoriLinkModel.AttentionCategory(value.category), subject: value.subject, folderLocalPath: value.folderLocalPath, raw: value.raw)
    }
}

extension YadoriLinkModel.BandwidthLimits {
    init(_ value: YadoriLinkFFI.BandwidthLimits) {
        self.init(uploadBytesPerSec: value.uploadBytesPerSec, downloadBytesPerSec: value.downloadBytesPerSec)
    }
}

extension YadoriLinkModel.BandwidthStatus {
    init(_ value: YadoriLinkFFI.BandwidthStatus) {
        self.init(limits: YadoriLinkModel.BandwidthLimits(value.limits), currentUploadBytesPerSec: value.currentUploadBytesPerSec, currentDownloadBytesPerSec: value.currentDownloadBytesPerSec)
    }
}

extension YadoriLinkModel.BrowserPurpose {
    init(_ value: YadoriLinkFFI.BrowserPurpose) {
        switch value {
        case .approveDevice: self = .approveDevice
        case .signIn: self = .signIn
        }
    }
}

extension YadoriLinkModel.ConflictReason {
    init(_ value: YadoriLinkFFI.ConflictReason) {
        switch value {
        case .concurrentEdit: self = .concurrentEdit
        case .folderAtPath: self = .folderAtPath
        }
    }
}

extension YadoriLinkModel.ConflictSummary {
    init(_ value: YadoriLinkFFI.ConflictSummary) {
        self.init(localPath: value.localPath, path: value.path, size: value.size, modifiedAt: value.modifiedAt, currentPath: value.currentPath, loserDeviceId: value.loserDeviceId, conflictTimestamp: value.conflictTimestamp, kind: YadoriLinkModel.EntryKind(value.kind), reason: YadoriLinkModel.ConflictReason(value.reason), holdsCompaction: value.holdsCompaction)
    }
}

extension YadoriLinkModel.CoreConfig {
    init(_ value: YadoriLinkFFI.CoreConfig) {
        self.init(daemonLaunch: YadoriLinkModel.DaemonLaunch(value.daemonLaunch))
    }
}

extension YadoriLinkModel.DaemonLaunch {
    init(_ value: YadoriLinkFFI.DaemonLaunch) {
        switch value {
        case let .spawnBinary(path): self = .spawnBinary(path: path)
        case let .launchAgent(label, fallbackBinary): self = .launchAgent(label: label, fallbackBinary: fallbackBinary)
        }
    }
}

extension YadoriLinkModel.DaemonStartOutcome {
    init(_ value: YadoriLinkFFI.DaemonStartOutcome) {
        switch value {
        case .alreadyRunning: self = .alreadyRunning
        case .started: self = .started
        }
    }
}

extension YadoriLinkModel.DaemonUnavailableReason {
    init(_ value: YadoriLinkFFI.DaemonUnavailableReason) {
        switch value {
        case .notRunning: self = .notRunning
        case .unresponsive: self = .unresponsive
        case let .protocolMismatch(clientVersion, daemonVersion): self = .protocolMismatch(clientVersion: clientVersion, daemonVersion: daemonVersion)
        }
    }
}

extension YadoriLinkModel.DesktopError {
    init(_ value: YadoriLinkFFI.DesktopError) {
        switch value {
        case let .NotSignedIn(message): self = .notSignedIn(message: message)
        case let .DaemonUnavailable(message, reason): self = .daemonUnavailable(message: message, reason: YadoriLinkModel.DaemonUnavailableReason(reason))
        case let .Network(message, kind): self = .network(message: message, kind: YadoriLinkModel.NetworkErrorKind(kind))
        case let .PermissionDenied(message, reason): self = .permissionDenied(message: message, reason: YadoriLinkModel.PermissionDeniedReason(reason))
        case let .DurabilityBlocked(message, groupIds, operationId, canForce): self = .durabilityBlocked(message: message, groupIds: groupIds, operationId: operationId, canForce: canForce)
        case let .InvalidInput(message, field): self = .invalidInput(message: message, field: field)
        case let .Internal(message, category): self = .internal(message: message, category: category)
        }
    }
}

extension YadoriLinkModel.DeviceRegistration {
    init(_ value: YadoriLinkFFI.DeviceRegistration) {
        self.init(deviceId: value.deviceId)
    }
}

extension YadoriLinkModel.DeviceSummary {
    init(_ value: YadoriLinkFFI.DeviceSummary) {
        self.init(deviceId: value.deviceId, displayName: value.displayName, online: value.online, lastSeen: value.lastSeen, isThisDevice: value.isThisDevice)
    }
}

extension YadoriLinkModel.DiagnosticsCollectionMode {
    init(_ value: YadoriLinkFFI.DiagnosticsCollectionMode) {
        switch value {
        case .daemon: self = .daemon
        case .daemonPartial: self = .daemonPartial
        case .offlineFallback: self = .offlineFallback
        }
    }
}

extension YadoriLinkModel.DiagnosticsExport {
    init(_ value: YadoriLinkFFI.DiagnosticsExport) {
        self.init(path: value.path, collectionMode: YadoriLinkModel.DiagnosticsCollectionMode(value.collectionMode), redactionCount: value.redactionCount)
    }
}

extension YadoriLinkModel.DurabilityEvidence {
    init(_ value: YadoriLinkFFI.DurabilityEvidence) {
        switch value {
        case .none: self = .none
        case .corroboratedIndex: self = .corroboratedIndex
        case .verifiedPayload: self = .verifiedPayload
        case .unknown: self = .unknown
        }
    }
}

extension YadoriLinkModel.DurabilityStatus {
    init(_ value: YadoriLinkFFI.DurabilityStatus) {
        switch value {
        case .protected: self = .protected
        case .protecting: self = .protecting
        case .atRisk: self = .atRisk
        case .unknown: self = .unknown
        }
    }
}

extension YadoriLinkModel.EntryKind {
    init(_ value: YadoriLinkFFI.EntryKind) {
        switch value {
        case .file: self = .file
        case .directory: self = .directory
        case .symlink: self = .symlink
        }
    }
}

extension YadoriLinkModel.EvictOutcome {
    init(_ value: YadoriLinkFFI.EvictOutcome) {
        self.init(evicted: value.evicted, blocksReclaimed: value.blocksReclaimed, bytesReclaimed: value.bytesReclaimed)
    }
}

extension YadoriLinkModel.FetchAvailability {
    init(_ value: YadoriLinkFFI.FetchAvailability) {
        switch value {
        case .availableNow: self = .availableNow
        case .unavailableNow: self = .unavailableNow
        case .unknown: self = .unknown
        }
    }
}

extension YadoriLinkModel.FileAvailability {
    init(_ value: YadoriLinkFFI.FileAvailability) {
        self.init(tracked: value.tracked, state: YadoriLinkModel.MaterializationState(value.state), pinned: value.pinned)
    }
}

extension YadoriLinkModel.FileVersion {
    init(_ value: YadoriLinkFFI.FileVersion) {
        self.init(versionSeq: value.versionSeq, size: value.size, modifiedAt: value.modifiedAt, state: value.state, originDeviceId: value.originDeviceId, unixMode: value.unixMode, isCurrent: value.isCurrent, kind: YadoriLinkModel.EntryKind(value.kind))
    }
}

extension YadoriLinkModel.FolderDetail {
    init(_ value: YadoriLinkFFI.FolderDetail) {
        self.init(summary: YadoriLinkModel.FolderSummary(value.summary), heldFiles: value.heldFiles.map { YadoriLinkModel.HeldFile($0) }, completeCopies: value.completeCopies.map { YadoriLinkModel.ReplicaCopy($0) })
    }
}

extension YadoriLinkModel.FolderMode {
    init(_ value: YadoriLinkFFI.FolderMode) {
        switch value {
        case .keepAll: self = .keepAll
        case .onDemand: self = .onDemand
        }
    }
}

extension YadoriLinkModel.FolderRestoreFailure {
    init(_ value: YadoriLinkFFI.FolderRestoreFailure) {
        self.init(path: value.path, error: value.error)
    }
}

extension YadoriLinkModel.FolderRestoreOutcome {
    init(_ value: YadoriLinkFFI.FolderRestoreOutcome) {
        self.init(restoredPaths: value.restoredPaths, failed: value.failed.map { YadoriLinkModel.FolderRestoreFailure($0) }, partial: value.partial)
    }
}

extension YadoriLinkModel.FolderState {
    init(_ value: YadoriLinkFFI.FolderState) {
        switch value {
        case .upToDate: self = .upToDate
        case .syncing: self = .syncing
        case .paused: self = .paused
        case .blocked: self = .blocked
        case .attention: self = .attention
        }
    }
}

extension YadoriLinkModel.FolderSummary {
    init(_ value: YadoriLinkFFI.FolderSummary) {
        self.init(localPath: value.localPath, groupId: value.groupId, name: value.name, mode: YadoriLinkModel.FolderMode(value.mode), state: YadoriLinkModel.FolderState(value.state), paused: value.paused, conflictCount: value.conflictCount, hydratedFileCount: value.hydratedFileCount, placeholderFileCount: value.placeholderFileCount, hydratingFileCount: value.hydratingFileCount, heldFileCount: value.heldFileCount, skippedSymlinkCount: value.skippedSymlinkCount, transfer: value.transfer.map { YadoriLinkModel.FolderTransferProgress($0) }, durability: YadoriLinkModel.DurabilityStatus(value.durability), durabilityEvidence: YadoriLinkModel.DurabilityEvidence(value.durabilityEvidence), localStorage: YadoriLinkModel.LocalStorageState(value.localStorage), fetchAvailability: YadoriLinkModel.FetchAvailability(value.fetchAvailability), fullReplicaDeviceIds: value.fullReplicaDeviceIds, policyStale: value.policyStale, ambiguous: value.ambiguous, ambiguousLocalPaths: value.ambiguousLocalPaths, degraded: value.degraded, degradedReason: value.degradedReason, volume: value.volume.map { YadoriLinkModel.VolumeSummary($0) })
    }
}

extension YadoriLinkModel.FolderTransferProgress {
    init(_ value: YadoriLinkFFI.FolderTransferProgress) {
        self.init(bytesDone: value.bytesDone, bytesTotal: value.bytesTotal, blocksDone: value.blocksDone, blocksTotal: value.blocksTotal, eta: value.eta)
    }
}

extension YadoriLinkModel.FreeSpace {
    init(_ value: YadoriLinkFFI.FreeSpace) {
        self.init(availableBytes: value.availableBytes, totalBytes: value.totalBytes, headroomBytes: value.headroomBytes, state: YadoriLinkModel.FreeSpaceState(value.state))
    }
}

extension YadoriLinkModel.FreeSpaceState {
    init(_ value: YadoriLinkFFI.FreeSpaceState) {
        switch value {
        case .ok: self = .ok
        case .low: self = .low
        case .critical: self = .critical
        case .unknown: self = .unknown
        }
    }
}

extension YadoriLinkModel.GcReport {
    init(_ value: YadoriLinkFFI.GcReport) {
        self.init(dryRun: value.dryRun, blocksDeleted: value.blocksDeleted, bytesReclaimed: value.bytesReclaimed)
    }
}

extension YadoriLinkModel.GroupSummary {
    init(_ value: YadoriLinkFFI.GroupSummary) {
        self.init(groupId: value.groupId, name: value.name)
    }
}

extension YadoriLinkModel.HandoffSummary {
    init(_ value: YadoriLinkFFI.HandoffSummary) {
        self.init(targetDeviceId: value.targetDeviceId, membershipGeneration: value.membershipGeneration, leaseId: value.leaseId)
    }
}

extension YadoriLinkModel.HeldFile {
    init(_ value: YadoriLinkFFI.HeldFile) {
        self.init(path: value.path, reason: value.reason, heldSince: value.heldSince)
    }
}

extension YadoriLinkModel.IncomingFile {
    init(_ value: YadoriLinkFFI.IncomingFile) {
        self.init(relativePath: value.relativePath, size: value.size)
    }
}

extension YadoriLinkModel.IncomingTransfer {
    init(_ value: YadoriLinkFFI.IncomingTransfer) {
        self.init(transferId: value.transferId, senderDeviceId: value.senderDeviceId, files: value.files.map { YadoriLinkModel.IncomingFile($0) }, totalSize: value.totalSize, offeredAt: value.offeredAt, status: YadoriLinkModel.IncomingTransferStatus(value.status))
    }
}

extension YadoriLinkModel.IncomingTransferStatus {
    init(_ value: YadoriLinkFFI.IncomingTransferStatus) {
        switch value {
        case .pending: self = .pending
        case .inProgress: self = .inProgress
        case .completed: self = .completed
        case let .other(raw): self = .other(raw: raw)
        }
    }
}

extension YadoriLinkModel.InviteStatus {
    init(_ value: YadoriLinkFFI.InviteStatus) {
        switch value {
        case .pending: self = .pending
        case let .other(raw): self = .other(raw: raw)
        }
    }
}

extension YadoriLinkModel.InviteSummary {
    init(_ value: YadoriLinkFFI.InviteSummary) {
        self.init(inviteId: value.inviteId, code: value.code, url: value.url, groupId: value.groupId, role: YadoriLinkModel.ShareRole(value.role), expiresAt: value.expiresAt, requiresApproval: value.requiresApproval)
    }
}

extension YadoriLinkModel.LinkOutcome {
    init(_ value: YadoriLinkFFI.LinkOutcome) {
        self.init(groupId: value.groupId, localPath: value.localPath, mode: YadoriLinkModel.FolderMode(value.mode))
    }
}

extension YadoriLinkModel.LocalStorageState {
    init(_ value: YadoriLinkFFI.LocalStorageState) {
        switch value {
        case .fullCopy: self = .fullCopy
        case .partiallyMaterialized: self = .partiallyMaterialized
        case .onDemand: self = .onDemand
        case .unknown: self = .unknown
        }
    }
}

extension YadoriLinkModel.LoginEvent {
    init(_ value: YadoriLinkFFI.LoginEvent) {
        switch value {
        case .enrolling: self = .enrolling
        case let .openBrowser(url, purpose): self = .openBrowser(url: url, purpose: YadoriLinkModel.BrowserPurpose(purpose))
        case let .waitingForApproval(expiresIn): self = .waitingForApproval(expiresIn: expiresIn)
        case .waitingForAuthorization: self = .waitingForAuthorization
        case let .showDeviceCode(verificationUri, userCode): self = .showDeviceCode(verificationUri: verificationUri, userCode: userCode)
        case let .signedIn(account): self = .signedIn(account: YadoriLinkModel.AccountStatus(account))
        case let .failed(error): self = .failed(error: YadoriLinkModel.DesktopError(error))
        case .cancelled: self = .cancelled
        }
    }
}

extension YadoriLinkModel.LoginFlow {
    init(_ value: YadoriLinkFFI.LoginFlow) {
        switch value {
        case .loopback: self = .loopback
        case .deviceCode: self = .deviceCode
        }
    }
}

extension YadoriLinkModel.LoginOptions {
    init(_ value: YadoriLinkFFI.LoginOptions) {
        self.init(flow: YadoriLinkModel.LoginFlow(value.flow), overallTimeout: value.overallTimeout)
    }
}

extension YadoriLinkModel.MaterializationState {
    init(_ value: YadoriLinkFFI.MaterializationState) {
        switch value {
        case .hydrated: self = .hydrated
        case .placeholder: self = .placeholder
        case .hydrating: self = .hydrating
        case .evicting: self = .evicting
        case .unknown: self = .unknown
        }
    }
}

extension YadoriLinkModel.MemberRelationship {
    init(_ value: YadoriLinkFFI.MemberRelationship) {
        switch value {
        case .you: self = .you
        case .yourOtherDevice: self = .yourOtherDevice
        case .ownersDevice: self = .ownersDevice
        case .invited: self = .invited
        }
    }
}

extension YadoriLinkModel.MemberStorage {
    init(_ value: YadoriLinkFFI.MemberStorage) {
        switch value {
        case .fullCopy: self = .fullCopy
        case .onDemand: self = .onDemand
        }
    }
}

extension YadoriLinkModel.MemberSummary {
    init(_ value: YadoriLinkFFI.MemberSummary) {
        self.init(deviceId: value.deviceId, deviceName: value.deviceName, role: YadoriLinkModel.ShareRole(value.role), relationship: YadoriLinkModel.MemberRelationship(value.relationship), storage: YadoriLinkModel.MemberStorage(value.storage), online: value.online, lastSeen: value.lastSeen)
    }
}

extension YadoriLinkModel.MembershipHandoff {
    init(_ value: YadoriLinkFFI.MembershipHandoff) {
        self.init(groupId: value.groupId, targetDeviceId: value.targetDeviceId, leaseId: value.leaseId, membershipGeneration: value.membershipGeneration)
    }
}

extension YadoriLinkModel.MembershipOutcome {
    init(_ value: YadoriLinkFFI.MembershipOutcome) {
        self.init(handoffs: value.handoffs.map { YadoriLinkModel.MembershipHandoff($0) }, forcedGroupIds: value.forcedGroupIds, unknownScopeOperationId: value.unknownScopeOperationId)
    }
}

extension YadoriLinkModel.NestedLinkRelation {
    init(_ value: YadoriLinkFFI.NestedLinkRelation) {
        switch value {
        case .ancestor: self = .ancestor
        case .descendant: self = .descendant
        case .same: self = .same
        }
    }
}

extension YadoriLinkModel.NetworkErrorKind {
    init(_ value: YadoriLinkFFI.NetworkErrorKind) {
        switch value {
        case .unreachable: self = .unreachable
        case .rateLimited: self = .rateLimited
        case .activationPendingReconciliation: self = .activationPendingReconciliation
        }
    }
}

extension YadoriLinkModel.OverallState {
    init(_ value: YadoriLinkFFI.OverallState) {
        switch value {
        case .healthy: self = .healthy
        case .attention: self = .attention
        case .degraded: self = .degraded
        case .unknown: self = .unknown
        }
    }
}

extension YadoriLinkModel.PeerReachability {
    init(_ value: YadoriLinkFFI.PeerReachability) {
        switch value {
        case .connecting: self = .connecting
        case .connected: self = .connected
        case .unreachable: self = .unreachable
        case .unknown: self = .unknown
        }
    }
}

extension YadoriLinkModel.PeerSummary {
    init(_ value: YadoriLinkFFI.PeerSummary) {
        self.init(deviceId: value.deviceId, reachability: YadoriLinkModel.PeerReachability(value.reachability), unreachableCategory: value.unreachableCategory.map { YadoriLinkModel.UnreachableCategory($0) }, route: YadoriLinkModel.RouteKind(value.route))
    }
}

extension YadoriLinkModel.PendingApprovalSummary {
    init(_ value: YadoriLinkFFI.PendingApprovalSummary) {
        self.init(groupId: value.groupId, groupName: value.groupName, deviceId: value.deviceId, requestedRole: value.requestedRole.map { YadoriLinkModel.ShareRole($0) })
    }
}

extension YadoriLinkModel.PendingInviteSummary {
    init(_ value: YadoriLinkFFI.PendingInviteSummary) {
        self.init(inviteId: value.inviteId, groupId: value.groupId, groupName: value.groupName, role: YadoriLinkModel.ShareRole(value.role), expiresAt: value.expiresAt, status: YadoriLinkModel.InviteStatus(value.status))
    }
}

extension YadoriLinkModel.PermissionDeniedReason {
    init(_ value: YadoriLinkFFI.PermissionDeniedReason) {
        switch value {
        case .sessionRejected: self = .sessionRejected
        case .forbidden: self = .forbidden
        case .quotaExceeded: self = .quotaExceeded
        case .credentialStoreUnusable: self = .credentialStoreUnusable
        }
    }
}

extension YadoriLinkModel.PreflightIssue {
    init(_ value: YadoriLinkFFI.PreflightIssue) {
        switch value {
        case .pathMissing: self = .pathMissing
        case .ignoreRulesUnreadable: self = .ignoreRulesUnreadable
        case let .notEmpty(entryCount, scanTruncated): self = .notEmpty(entryCount: entryCount, scanTruncated: scanTruncated)
        case let .lowFreeSpace(availableBytes, headroomBytes): self = .lowFreeSpace(availableBytes: availableBytes, headroomBytes: headroomBytes)
        case let .criticalFreeSpace(availableBytes, headroomBytes): self = .criticalFreeSpace(availableBytes: availableBytes, headroomBytes: headroomBytes)
        case let .nestedLink(otherPath, relation): self = .nestedLink(otherPath: otherPath, relation: YadoriLinkModel.NestedLinkRelation(relation))
        case let .cloudProviderFolder(provider): self = .cloudProviderFolder(provider: provider)
        case .filesystemRoot: self = .filesystemRoot
        case .homeDirectory: self = .homeDirectory
        case let .reservedName(path): self = .reservedName(path: path)
        }
    }
}

extension YadoriLinkModel.PreflightResult {
    init(_ value: YadoriLinkFFI.PreflightResult) {
        self.init(resolvedPath: value.resolvedPath, pathExists: value.pathExists, isDirectory: value.isDirectory, entryCount: value.entryCount, ignoredEntryCount: value.ignoredEntryCount, totalSizeBytes: value.totalSizeBytes, scanTruncated: value.scanTruncated, freeSpace: value.freeSpace.map { YadoriLinkModel.FreeSpace($0) }, issues: value.issues.map { YadoriLinkModel.PreflightIssue($0) }, requiresAcknowledgement: value.requiresAcknowledgement)
    }
}

extension YadoriLinkModel.ReceivedTransfer {
    init(_ value: YadoriLinkFFI.ReceivedTransfer) {
        self.init(destinationDir: value.destinationDir, filesReceived: value.filesReceived, bytesReceived: value.bytesReceived)
    }
}

extension YadoriLinkModel.RecentError {
    init(_ value: YadoriLinkFFI.RecentError) {
        self.init(category: value.category, at: value.at, context: value.context)
    }
}

extension YadoriLinkModel.ReplicaCopy {
    init(_ value: YadoriLinkFFI.ReplicaCopy) {
        self.init(deviceId: value.deviceId, reachability: YadoriLinkModel.PeerReachability(value.reachability), route: YadoriLinkModel.RouteKind(value.route))
    }
}

extension YadoriLinkModel.RevokeEdgeOutcome {
    init(_ value: YadoriLinkFFI.RevokeEdgeOutcome) {
        switch value {
        case let .revoked(outcome): self = .revoked(outcome: YadoriLinkModel.MembershipOutcome(outcome))
        case .alreadyRevoked: self = .alreadyRevoked
        }
    }
}

extension YadoriLinkModel.RouteKind {
    init(_ value: YadoriLinkFFI.RouteKind) {
        switch value {
        case .direct: self = .direct
        case .relay: self = .relay
        case .unknown: self = .unknown
        }
    }
}

extension YadoriLinkModel.SentTransfer {
    init(_ value: YadoriLinkFFI.SentTransfer) {
        self.init(transferId: value.transferId, filesOffered: value.filesOffered, totalSize: value.totalSize)
    }
}

extension YadoriLinkModel.ShareEdgeState {
    init(_ value: YadoriLinkFFI.ShareEdgeState) {
        switch value {
        case .active: self = .active
        case .pendingApproval: self = .pendingApproval
        case let .other(raw): self = .other(raw: raw)
        }
    }
}

extension YadoriLinkModel.ShareRole {
    init(_ value: YadoriLinkFFI.ShareRole) {
        switch value {
        case .owner: self = .owner
        case .editor: self = .editor
        case .viewer: self = .viewer
        case let .other(raw): self = .other(raw: raw)
        }
    }
}

extension YadoriLinkModel.ShareSummary {
    init(_ value: YadoriLinkFFI.ShareSummary) {
        self.init(edgeId: value.edgeId, groupId: value.groupId, groupName: value.groupName, deviceId: value.deviceId, state: YadoriLinkModel.ShareEdgeState(value.state), role: value.role.map { YadoriLinkModel.ShareRole($0) })
    }
}

extension YadoriLinkModel.SignInState {
    init(_ value: YadoriLinkFFI.SignInState) {
        switch value {
        case .signedOut: self = .signedOut
        case .signedIn: self = .signedIn
        case let .credentialStoreUnusable(message): self = .credentialStoreUnusable(message: message)
        }
    }
}

extension YadoriLinkModel.SignOutKind {
    init(_ value: YadoriLinkFFI.SignOutKind) {
        switch value {
        case let .revoked(grantsRevoked): self = .revoked(grantsRevoked: grantsRevoked)
        case .alreadyRevoked: self = .alreadyRevoked
        case .confirmedRevokedAfterRejection: self = .confirmedRevokedAfterRejection
        }
    }
}

extension YadoriLinkModel.SignOutOutcome {
    init(_ value: YadoriLinkFFI.SignOutOutcome) {
        self.init(kind: YadoriLinkModel.SignOutKind(value.kind))
    }
}

extension YadoriLinkModel.StatusSnapshot {
    init(_ value: YadoriLinkFFI.StatusSnapshot) {
        self.init(capturedAt: value.capturedAt, overall: YadoriLinkModel.OverallState(value.overall), attentionReasons: value.attentionReasons.map { YadoriLinkModel.AttentionReason($0) }, thisDeviceId: value.thisDeviceId, folders: value.folders.map { YadoriLinkModel.FolderSummary($0) }, peers: value.peers.map { YadoriLinkModel.PeerSummary($0) }, transfers: value.transfers.map { YadoriLinkModel.TransferSummary($0) }, bandwidth: YadoriLinkModel.BandwidthStatus(value.bandwidth), volumes: value.volumes.map { YadoriLinkModel.VolumeSummary($0) }, storage: YadoriLinkModel.StorageSummary(value.storage), update: YadoriLinkModel.UpdateBadge(value.update), recentErrors: value.recentErrors.map { YadoriLinkModel.RecentError($0) })
    }
}

extension YadoriLinkModel.StatusUpdate {
    init(_ value: YadoriLinkFFI.StatusUpdate) {
        switch value {
        case let .snapshot(snapshot): self = .snapshot(snapshot: YadoriLinkModel.StatusSnapshot(snapshot))
        case let .unavailable(error): self = .unavailable(error: YadoriLinkModel.DesktopError(error))
        }
    }
}

extension YadoriLinkModel.StorageModeOutcome {
    init(_ value: YadoriLinkFFI.StorageModeOutcome) {
        self.init(changed: value.changed, handoff: value.handoff.map { YadoriLinkModel.HandoffSummary($0) })
    }
}

extension YadoriLinkModel.StorageSummary {
    init(_ value: YadoriLinkFFI.StorageSummary) {
        self.init(blockStoreTotalBytes: value.blockStoreTotalBytes, blockCount: value.blockCount, lastGcAt: value.lastGcAt, reclaimableEstimateBytes: value.reclaimableEstimateBytes)
    }
}

extension YadoriLinkModel.TransferSummary {
    init(_ value: YadoriLinkFFI.TransferSummary) {
        self.init(groupId: value.groupId, folderLocalPath: value.folderLocalPath, path: value.path, bytesDone: value.bytesDone, bytesTotal: value.bytesTotal, blocksDone: value.blocksDone, blocksTotal: value.blocksTotal, sourceDeviceId: value.sourceDeviceId, startedAt: value.startedAt)
    }
}

extension YadoriLinkModel.TrashedFile {
    init(_ value: YadoriLinkFFI.TrashedFile) {
        self.init(localPath: value.localPath, path: value.path, versionSeq: value.versionSeq, lastKnownSize: value.lastKnownSize, originDeviceId: value.originDeviceId, deletedAt: value.deletedAt, kind: YadoriLinkModel.EntryKind(value.kind), deletedByOperation: value.deletedByOperation)
    }
}

extension YadoriLinkModel.UnlinkOutcome {
    init(_ value: YadoriLinkFFI.UnlinkOutcome) {
        self.init(handoff: value.handoff.map { YadoriLinkModel.HandoffSummary($0) })
    }
}

extension YadoriLinkModel.UnreachableCategory {
    init(_ value: YadoriLinkFFI.UnreachableCategory) {
        switch value {
        case .noCandidates: self = .noCandidates
        case .noResponse: self = .noResponse
        case .udpBlocked: self = .udpBlocked
        case .handshakeRefused: self = .handshakeRefused
        }
    }
}

extension YadoriLinkModel.UpdateBadge {
    init(_ value: YadoriLinkFFI.UpdateBadge) {
        self.init(state: YadoriLinkModel.UpdateState(value.state), availableVersion: value.availableVersion, mandatory: value.mandatory, waitingForSafePoint: value.waitingForSafePoint, lastErrorCategory: value.lastErrorCategory, channel: value.channel, installSource: value.installSource, holdbackReason: value.holdbackReason)
    }
}

extension YadoriLinkModel.UpdateConfig {
    init(_ value: YadoriLinkFFI.UpdateConfig) {
        self.init(automaticChecks: value.automaticChecks, installMode: YadoriLinkModel.UpdateInstallMode(value.installMode))
    }
}

extension YadoriLinkModel.UpdateInstallMode {
    init(_ value: YadoriLinkFFI.UpdateInstallMode) {
        switch value {
        case .automatic: self = .automatic
        case .manual: self = .manual
        case let .other(raw): self = .other(raw: raw)
        }
    }
}

extension YadoriLinkModel.UpdateInstallOutcome {
    init(_ value: YadoriLinkFFI.UpdateInstallOutcome) {
        switch value {
        case .installing: self = .installing
        case .deferred: self = .deferred
        case let .storeManaged(guidance): self = .storeManaged(guidance: guidance)
        case let .other(raw): self = .other(raw: raw)
        }
    }
}

extension YadoriLinkModel.UpdateState {
    init(_ value: YadoriLinkFFI.UpdateState) {
        switch value {
        case .idle: self = .idle
        case .checking: self = .checking
        case .available: self = .available
        case .heldBack: self = .heldBack
        case .killSwitched: self = .killSwitched
        case .downloading: self = .downloading
        case .downloaded: self = .downloaded
        case .verified: self = .verified
        case .installing: self = .installing
        case .failed: self = .failed
        case .deferred: self = .deferred
        case .upToDate: self = .upToDate
        case let .unknown(raw): self = .unknown(raw: raw)
        }
    }
}

extension YadoriLinkModel.UpdateStatus {
    init(_ value: YadoriLinkFFI.UpdateStatus) {
        self.init(currentVersion: value.currentVersion, channel: value.channel, installSource: value.installSource, lastCheckedAt: value.lastCheckedAt, state: YadoriLinkModel.UpdateState(value.state), availableVersion: value.availableVersion, releaseNotesUrl: value.releaseNotesUrl, mandatory: value.mandatory, holdbackReason: value.holdbackReason, waitingForSafePoint: value.waitingForSafePoint, lastErrorCategory: value.lastErrorCategory, lastErrorMessage: value.lastErrorMessage, config: YadoriLinkModel.UpdateConfig(value.config))
    }
}

extension YadoriLinkModel.VolumeSummary {
    init(_ value: YadoriLinkFFI.VolumeSummary) {
        self.init(path: value.path, state: YadoriLinkModel.FreeSpaceState(value.state), availableBytes: value.availableBytes, headroomBytes: value.headroomBytes)
    }
}

extension YadoriLinkFFI.AcceptInviteOutcome {
    init(_ value: YadoriLinkModel.AcceptInviteOutcome) {
        self.init(groupId: value.groupId, localPath: value.localPath, awaitingApproval: value.awaitingApproval)
    }
}

extension YadoriLinkFFI.AccountDeletionRequest {
    init(_ value: YadoriLinkModel.AccountDeletionRequest) {
        self.init(confirmationToken: value.confirmationToken)
    }
}

extension YadoriLinkFFI.AccountDeletionState {
    init(_ value: YadoriLinkModel.AccountDeletionState) {
        switch value {
        case .active: self = .active
        case .requested: self = .requested
        case .grace: self = .grace
        case let .other(raw): self = .other(raw: raw)
        }
    }
}

extension YadoriLinkFFI.AccountDeletionStatus {
    init(_ value: YadoriLinkModel.AccountDeletionStatus) {
        self.init(state: YadoriLinkFFI.AccountDeletionState(value.state), graceExpiresAt: value.graceExpiresAt, remaining: value.remaining)
    }
}

extension YadoriLinkFFI.AccountStatus {
    init(_ value: YadoriLinkModel.AccountStatus) {
        self.init(signIn: YadoriLinkFFI.SignInState(value.signIn), clientId: value.clientId, thisDeviceId: value.thisDeviceId, deviceRegistered: value.deviceRegistered, defaultDeviceName: value.defaultDeviceName, hasLinkedFolders: value.hasLinkedFolders)
    }
}

extension YadoriLinkFFI.ApproveOutcome {
    init(_ value: YadoriLinkModel.ApproveOutcome) {
        switch value {
        case .approved: self = .approved
        case .alreadyActive: self = .alreadyActive
        case let .unrecognized(raw): self = .unrecognized(raw: raw)
        }
    }
}

extension YadoriLinkFFI.AssignableRole {
    init(_ value: YadoriLinkModel.AssignableRole) {
        switch value {
        case .viewer: self = .viewer
        case .editor: self = .editor
        }
    }
}

extension YadoriLinkFFI.AttentionCategory {
    init(_ value: YadoriLinkModel.AttentionCategory) {
        switch value {
        case .degraded: self = .degraded
        case .durabilityAtRisk: self = .durabilityAtRisk
        case .durabilityUnknown: self = .durabilityUnknown
        case .fetchUnavailable: self = .fetchUnavailable
        case .fetchAvailabilityUnknown: self = .fetchAvailabilityUnknown
        case .conflict: self = .conflict
        case .held: self = .held
        case .lowDiskCritical: self = .lowDiskCritical
        case .lowDisk: self = .lowDisk
        case .peerDisconnected: self = .peerDisconnected
        case .recentError: self = .recentError
        case .updateFailed: self = .updateFailed
        case .unrecognized: self = .unrecognized
        }
    }
}

extension YadoriLinkFFI.AttentionReason {
    init(_ value: YadoriLinkModel.AttentionReason) {
        self.init(category: YadoriLinkFFI.AttentionCategory(value.category), subject: value.subject, folderLocalPath: value.folderLocalPath, raw: value.raw)
    }
}

extension YadoriLinkFFI.BandwidthLimits {
    init(_ value: YadoriLinkModel.BandwidthLimits) {
        self.init(uploadBytesPerSec: value.uploadBytesPerSec, downloadBytesPerSec: value.downloadBytesPerSec)
    }
}

extension YadoriLinkFFI.BandwidthStatus {
    init(_ value: YadoriLinkModel.BandwidthStatus) {
        self.init(limits: YadoriLinkFFI.BandwidthLimits(value.limits), currentUploadBytesPerSec: value.currentUploadBytesPerSec, currentDownloadBytesPerSec: value.currentDownloadBytesPerSec)
    }
}

extension YadoriLinkFFI.BrowserPurpose {
    init(_ value: YadoriLinkModel.BrowserPurpose) {
        switch value {
        case .approveDevice: self = .approveDevice
        case .signIn: self = .signIn
        }
    }
}

extension YadoriLinkFFI.ConflictReason {
    init(_ value: YadoriLinkModel.ConflictReason) {
        switch value {
        case .concurrentEdit: self = .concurrentEdit
        case .folderAtPath: self = .folderAtPath
        }
    }
}

extension YadoriLinkFFI.ConflictSummary {
    init(_ value: YadoriLinkModel.ConflictSummary) {
        self.init(localPath: value.localPath, path: value.path, size: value.size, modifiedAt: value.modifiedAt, currentPath: value.currentPath, loserDeviceId: value.loserDeviceId, conflictTimestamp: value.conflictTimestamp, kind: YadoriLinkFFI.EntryKind(value.kind), reason: YadoriLinkFFI.ConflictReason(value.reason), holdsCompaction: value.holdsCompaction)
    }
}

extension YadoriLinkFFI.CoreConfig {
    init(_ value: YadoriLinkModel.CoreConfig) {
        self.init(daemonLaunch: YadoriLinkFFI.DaemonLaunch(value.daemonLaunch))
    }
}

extension YadoriLinkFFI.DaemonLaunch {
    init(_ value: YadoriLinkModel.DaemonLaunch) {
        switch value {
        case let .spawnBinary(path): self = .spawnBinary(path: path)
        case let .launchAgent(label, fallbackBinary): self = .launchAgent(label: label, fallbackBinary: fallbackBinary)
        }
    }
}

extension YadoriLinkFFI.DaemonStartOutcome {
    init(_ value: YadoriLinkModel.DaemonStartOutcome) {
        switch value {
        case .alreadyRunning: self = .alreadyRunning
        case .started: self = .started
        }
    }
}

extension YadoriLinkFFI.DaemonUnavailableReason {
    init(_ value: YadoriLinkModel.DaemonUnavailableReason) {
        switch value {
        case .notRunning: self = .notRunning
        case .unresponsive: self = .unresponsive
        case let .protocolMismatch(clientVersion, daemonVersion): self = .protocolMismatch(clientVersion: clientVersion, daemonVersion: daemonVersion)
        }
    }
}

extension YadoriLinkFFI.DesktopError {
    init(_ value: YadoriLinkModel.DesktopError) {
        switch value {
        case let .notSignedIn(message): self = .NotSignedIn(message: message)
        case let .daemonUnavailable(message, reason): self = .DaemonUnavailable(message: message, reason: YadoriLinkFFI.DaemonUnavailableReason(reason))
        case let .network(message, kind): self = .Network(message: message, kind: YadoriLinkFFI.NetworkErrorKind(kind))
        case let .permissionDenied(message, reason): self = .PermissionDenied(message: message, reason: YadoriLinkFFI.PermissionDeniedReason(reason))
        case let .durabilityBlocked(message, groupIds, operationId, canForce): self = .DurabilityBlocked(message: message, groupIds: groupIds, operationId: operationId, canForce: canForce)
        case let .invalidInput(message, field): self = .InvalidInput(message: message, field: field)
        case let .internal(message, category): self = .Internal(message: message, category: category)
        }
    }
}

extension YadoriLinkFFI.DeviceRegistration {
    init(_ value: YadoriLinkModel.DeviceRegistration) {
        self.init(deviceId: value.deviceId)
    }
}

extension YadoriLinkFFI.DeviceSummary {
    init(_ value: YadoriLinkModel.DeviceSummary) {
        self.init(deviceId: value.deviceId, displayName: value.displayName, online: value.online, lastSeen: value.lastSeen, isThisDevice: value.isThisDevice)
    }
}

extension YadoriLinkFFI.DiagnosticsCollectionMode {
    init(_ value: YadoriLinkModel.DiagnosticsCollectionMode) {
        switch value {
        case .daemon: self = .daemon
        case .daemonPartial: self = .daemonPartial
        case .offlineFallback: self = .offlineFallback
        }
    }
}

extension YadoriLinkFFI.DiagnosticsExport {
    init(_ value: YadoriLinkModel.DiagnosticsExport) {
        self.init(path: value.path, collectionMode: YadoriLinkFFI.DiagnosticsCollectionMode(value.collectionMode), redactionCount: value.redactionCount)
    }
}

extension YadoriLinkFFI.DurabilityEvidence {
    init(_ value: YadoriLinkModel.DurabilityEvidence) {
        switch value {
        case .none: self = .none
        case .corroboratedIndex: self = .corroboratedIndex
        case .verifiedPayload: self = .verifiedPayload
        case .unknown: self = .unknown
        }
    }
}

extension YadoriLinkFFI.DurabilityStatus {
    init(_ value: YadoriLinkModel.DurabilityStatus) {
        switch value {
        case .protected: self = .protected
        case .protecting: self = .protecting
        case .atRisk: self = .atRisk
        case .unknown: self = .unknown
        }
    }
}

extension YadoriLinkFFI.EntryKind {
    init(_ value: YadoriLinkModel.EntryKind) {
        switch value {
        case .file: self = .file
        case .directory: self = .directory
        case .symlink: self = .symlink
        }
    }
}

extension YadoriLinkFFI.EvictOutcome {
    init(_ value: YadoriLinkModel.EvictOutcome) {
        self.init(evicted: value.evicted, blocksReclaimed: value.blocksReclaimed, bytesReclaimed: value.bytesReclaimed)
    }
}

extension YadoriLinkFFI.FetchAvailability {
    init(_ value: YadoriLinkModel.FetchAvailability) {
        switch value {
        case .availableNow: self = .availableNow
        case .unavailableNow: self = .unavailableNow
        case .unknown: self = .unknown
        }
    }
}

extension YadoriLinkFFI.FileAvailability {
    init(_ value: YadoriLinkModel.FileAvailability) {
        self.init(tracked: value.tracked, state: YadoriLinkFFI.MaterializationState(value.state), pinned: value.pinned)
    }
}

extension YadoriLinkFFI.FileVersion {
    init(_ value: YadoriLinkModel.FileVersion) {
        self.init(versionSeq: value.versionSeq, size: value.size, modifiedAt: value.modifiedAt, state: value.state, originDeviceId: value.originDeviceId, unixMode: value.unixMode, isCurrent: value.isCurrent, kind: YadoriLinkFFI.EntryKind(value.kind))
    }
}

extension YadoriLinkFFI.FolderDetail {
    init(_ value: YadoriLinkModel.FolderDetail) {
        self.init(summary: YadoriLinkFFI.FolderSummary(value.summary), heldFiles: value.heldFiles.map { YadoriLinkFFI.HeldFile($0) }, completeCopies: value.completeCopies.map { YadoriLinkFFI.ReplicaCopy($0) })
    }
}

extension YadoriLinkFFI.FolderMode {
    init(_ value: YadoriLinkModel.FolderMode) {
        switch value {
        case .keepAll: self = .keepAll
        case .onDemand: self = .onDemand
        }
    }
}

extension YadoriLinkFFI.FolderRestoreFailure {
    init(_ value: YadoriLinkModel.FolderRestoreFailure) {
        self.init(path: value.path, error: value.error)
    }
}

extension YadoriLinkFFI.FolderRestoreOutcome {
    init(_ value: YadoriLinkModel.FolderRestoreOutcome) {
        self.init(restoredPaths: value.restoredPaths, failed: value.failed.map { YadoriLinkFFI.FolderRestoreFailure($0) }, partial: value.partial)
    }
}

extension YadoriLinkFFI.FolderState {
    init(_ value: YadoriLinkModel.FolderState) {
        switch value {
        case .upToDate: self = .upToDate
        case .syncing: self = .syncing
        case .paused: self = .paused
        case .blocked: self = .blocked
        case .attention: self = .attention
        }
    }
}

extension YadoriLinkFFI.FolderSummary {
    init(_ value: YadoriLinkModel.FolderSummary) {
        self.init(localPath: value.localPath, groupId: value.groupId, name: value.name, mode: YadoriLinkFFI.FolderMode(value.mode), state: YadoriLinkFFI.FolderState(value.state), paused: value.paused, conflictCount: value.conflictCount, hydratedFileCount: value.hydratedFileCount, placeholderFileCount: value.placeholderFileCount, hydratingFileCount: value.hydratingFileCount, heldFileCount: value.heldFileCount, skippedSymlinkCount: value.skippedSymlinkCount, transfer: value.transfer.map { YadoriLinkFFI.FolderTransferProgress($0) }, durability: YadoriLinkFFI.DurabilityStatus(value.durability), durabilityEvidence: YadoriLinkFFI.DurabilityEvidence(value.durabilityEvidence), localStorage: YadoriLinkFFI.LocalStorageState(value.localStorage), fetchAvailability: YadoriLinkFFI.FetchAvailability(value.fetchAvailability), fullReplicaDeviceIds: value.fullReplicaDeviceIds, policyStale: value.policyStale, ambiguous: value.ambiguous, ambiguousLocalPaths: value.ambiguousLocalPaths, degraded: value.degraded, degradedReason: value.degradedReason, volume: value.volume.map { YadoriLinkFFI.VolumeSummary($0) })
    }
}

extension YadoriLinkFFI.FolderTransferProgress {
    init(_ value: YadoriLinkModel.FolderTransferProgress) {
        self.init(bytesDone: value.bytesDone, bytesTotal: value.bytesTotal, blocksDone: value.blocksDone, blocksTotal: value.blocksTotal, eta: value.eta)
    }
}

extension YadoriLinkFFI.FreeSpace {
    init(_ value: YadoriLinkModel.FreeSpace) {
        self.init(availableBytes: value.availableBytes, totalBytes: value.totalBytes, headroomBytes: value.headroomBytes, state: YadoriLinkFFI.FreeSpaceState(value.state))
    }
}

extension YadoriLinkFFI.FreeSpaceState {
    init(_ value: YadoriLinkModel.FreeSpaceState) {
        switch value {
        case .ok: self = .ok
        case .low: self = .low
        case .critical: self = .critical
        case .unknown: self = .unknown
        }
    }
}

extension YadoriLinkFFI.GcReport {
    init(_ value: YadoriLinkModel.GcReport) {
        self.init(dryRun: value.dryRun, blocksDeleted: value.blocksDeleted, bytesReclaimed: value.bytesReclaimed)
    }
}

extension YadoriLinkFFI.GroupSummary {
    init(_ value: YadoriLinkModel.GroupSummary) {
        self.init(groupId: value.groupId, name: value.name)
    }
}

extension YadoriLinkFFI.HandoffSummary {
    init(_ value: YadoriLinkModel.HandoffSummary) {
        self.init(targetDeviceId: value.targetDeviceId, membershipGeneration: value.membershipGeneration, leaseId: value.leaseId)
    }
}

extension YadoriLinkFFI.HeldFile {
    init(_ value: YadoriLinkModel.HeldFile) {
        self.init(path: value.path, reason: value.reason, heldSince: value.heldSince)
    }
}

extension YadoriLinkFFI.IncomingFile {
    init(_ value: YadoriLinkModel.IncomingFile) {
        self.init(relativePath: value.relativePath, size: value.size)
    }
}

extension YadoriLinkFFI.IncomingTransfer {
    init(_ value: YadoriLinkModel.IncomingTransfer) {
        self.init(transferId: value.transferId, senderDeviceId: value.senderDeviceId, files: value.files.map { YadoriLinkFFI.IncomingFile($0) }, totalSize: value.totalSize, offeredAt: value.offeredAt, status: YadoriLinkFFI.IncomingTransferStatus(value.status))
    }
}

extension YadoriLinkFFI.IncomingTransferStatus {
    init(_ value: YadoriLinkModel.IncomingTransferStatus) {
        switch value {
        case .pending: self = .pending
        case .inProgress: self = .inProgress
        case .completed: self = .completed
        case let .other(raw): self = .other(raw: raw)
        }
    }
}

extension YadoriLinkFFI.InviteStatus {
    init(_ value: YadoriLinkModel.InviteStatus) {
        switch value {
        case .pending: self = .pending
        case let .other(raw): self = .other(raw: raw)
        }
    }
}

extension YadoriLinkFFI.InviteSummary {
    init(_ value: YadoriLinkModel.InviteSummary) {
        self.init(inviteId: value.inviteId, code: value.code, url: value.url, groupId: value.groupId, role: YadoriLinkFFI.ShareRole(value.role), expiresAt: value.expiresAt, requiresApproval: value.requiresApproval)
    }
}

extension YadoriLinkFFI.LinkOutcome {
    init(_ value: YadoriLinkModel.LinkOutcome) {
        self.init(groupId: value.groupId, localPath: value.localPath, mode: YadoriLinkFFI.FolderMode(value.mode))
    }
}

extension YadoriLinkFFI.LocalStorageState {
    init(_ value: YadoriLinkModel.LocalStorageState) {
        switch value {
        case .fullCopy: self = .fullCopy
        case .partiallyMaterialized: self = .partiallyMaterialized
        case .onDemand: self = .onDemand
        case .unknown: self = .unknown
        }
    }
}

extension YadoriLinkFFI.LoginEvent {
    init(_ value: YadoriLinkModel.LoginEvent) {
        switch value {
        case .enrolling: self = .enrolling
        case let .openBrowser(url, purpose): self = .openBrowser(url: url, purpose: YadoriLinkFFI.BrowserPurpose(purpose))
        case let .waitingForApproval(expiresIn): self = .waitingForApproval(expiresIn: expiresIn)
        case .waitingForAuthorization: self = .waitingForAuthorization
        case let .showDeviceCode(verificationUri, userCode): self = .showDeviceCode(verificationUri: verificationUri, userCode: userCode)
        case let .signedIn(account): self = .signedIn(account: YadoriLinkFFI.AccountStatus(account))
        case let .failed(error): self = .failed(error: YadoriLinkFFI.DesktopError(error))
        case .cancelled: self = .cancelled
        }
    }
}

extension YadoriLinkFFI.LoginFlow {
    init(_ value: YadoriLinkModel.LoginFlow) {
        switch value {
        case .loopback: self = .loopback
        case .deviceCode: self = .deviceCode
        }
    }
}

extension YadoriLinkFFI.LoginOptions {
    init(_ value: YadoriLinkModel.LoginOptions) {
        self.init(flow: YadoriLinkFFI.LoginFlow(value.flow), overallTimeout: value.overallTimeout)
    }
}

extension YadoriLinkFFI.MaterializationState {
    init(_ value: YadoriLinkModel.MaterializationState) {
        switch value {
        case .hydrated: self = .hydrated
        case .placeholder: self = .placeholder
        case .hydrating: self = .hydrating
        case .evicting: self = .evicting
        case .unknown: self = .unknown
        }
    }
}

extension YadoriLinkFFI.MemberRelationship {
    init(_ value: YadoriLinkModel.MemberRelationship) {
        switch value {
        case .you: self = .you
        case .yourOtherDevice: self = .yourOtherDevice
        case .ownersDevice: self = .ownersDevice
        case .invited: self = .invited
        }
    }
}

extension YadoriLinkFFI.MemberStorage {
    init(_ value: YadoriLinkModel.MemberStorage) {
        switch value {
        case .fullCopy: self = .fullCopy
        case .onDemand: self = .onDemand
        }
    }
}

extension YadoriLinkFFI.MemberSummary {
    init(_ value: YadoriLinkModel.MemberSummary) {
        self.init(deviceId: value.deviceId, deviceName: value.deviceName, role: YadoriLinkFFI.ShareRole(value.role), relationship: YadoriLinkFFI.MemberRelationship(value.relationship), storage: YadoriLinkFFI.MemberStorage(value.storage), online: value.online, lastSeen: value.lastSeen)
    }
}

extension YadoriLinkFFI.MembershipHandoff {
    init(_ value: YadoriLinkModel.MembershipHandoff) {
        self.init(groupId: value.groupId, targetDeviceId: value.targetDeviceId, leaseId: value.leaseId, membershipGeneration: value.membershipGeneration)
    }
}

extension YadoriLinkFFI.MembershipOutcome {
    init(_ value: YadoriLinkModel.MembershipOutcome) {
        self.init(handoffs: value.handoffs.map { YadoriLinkFFI.MembershipHandoff($0) }, forcedGroupIds: value.forcedGroupIds, unknownScopeOperationId: value.unknownScopeOperationId)
    }
}

extension YadoriLinkFFI.NestedLinkRelation {
    init(_ value: YadoriLinkModel.NestedLinkRelation) {
        switch value {
        case .ancestor: self = .ancestor
        case .descendant: self = .descendant
        case .same: self = .same
        }
    }
}

extension YadoriLinkFFI.NetworkErrorKind {
    init(_ value: YadoriLinkModel.NetworkErrorKind) {
        switch value {
        case .unreachable: self = .unreachable
        case .rateLimited: self = .rateLimited
        case .activationPendingReconciliation: self = .activationPendingReconciliation
        }
    }
}

extension YadoriLinkFFI.OverallState {
    init(_ value: YadoriLinkModel.OverallState) {
        switch value {
        case .healthy: self = .healthy
        case .attention: self = .attention
        case .degraded: self = .degraded
        case .unknown: self = .unknown
        }
    }
}

extension YadoriLinkFFI.PeerReachability {
    init(_ value: YadoriLinkModel.PeerReachability) {
        switch value {
        case .connecting: self = .connecting
        case .connected: self = .connected
        case .unreachable: self = .unreachable
        case .unknown: self = .unknown
        }
    }
}

extension YadoriLinkFFI.PeerSummary {
    init(_ value: YadoriLinkModel.PeerSummary) {
        self.init(deviceId: value.deviceId, reachability: YadoriLinkFFI.PeerReachability(value.reachability), unreachableCategory: value.unreachableCategory.map { YadoriLinkFFI.UnreachableCategory($0) }, route: YadoriLinkFFI.RouteKind(value.route))
    }
}

extension YadoriLinkFFI.PendingApprovalSummary {
    init(_ value: YadoriLinkModel.PendingApprovalSummary) {
        self.init(groupId: value.groupId, groupName: value.groupName, deviceId: value.deviceId, requestedRole: value.requestedRole.map { YadoriLinkFFI.ShareRole($0) })
    }
}

extension YadoriLinkFFI.PendingInviteSummary {
    init(_ value: YadoriLinkModel.PendingInviteSummary) {
        self.init(inviteId: value.inviteId, groupId: value.groupId, groupName: value.groupName, role: YadoriLinkFFI.ShareRole(value.role), expiresAt: value.expiresAt, status: YadoriLinkFFI.InviteStatus(value.status))
    }
}

extension YadoriLinkFFI.PermissionDeniedReason {
    init(_ value: YadoriLinkModel.PermissionDeniedReason) {
        switch value {
        case .sessionRejected: self = .sessionRejected
        case .forbidden: self = .forbidden
        case .quotaExceeded: self = .quotaExceeded
        case .credentialStoreUnusable: self = .credentialStoreUnusable
        }
    }
}

extension YadoriLinkFFI.PreflightIssue {
    init(_ value: YadoriLinkModel.PreflightIssue) {
        switch value {
        case .pathMissing: self = .pathMissing
        case .ignoreRulesUnreadable: self = .ignoreRulesUnreadable
        case let .notEmpty(entryCount, scanTruncated): self = .notEmpty(entryCount: entryCount, scanTruncated: scanTruncated)
        case let .lowFreeSpace(availableBytes, headroomBytes): self = .lowFreeSpace(availableBytes: availableBytes, headroomBytes: headroomBytes)
        case let .criticalFreeSpace(availableBytes, headroomBytes): self = .criticalFreeSpace(availableBytes: availableBytes, headroomBytes: headroomBytes)
        case let .nestedLink(otherPath, relation): self = .nestedLink(otherPath: otherPath, relation: YadoriLinkFFI.NestedLinkRelation(relation))
        case let .cloudProviderFolder(provider): self = .cloudProviderFolder(provider: provider)
        case .filesystemRoot: self = .filesystemRoot
        case .homeDirectory: self = .homeDirectory
        case let .reservedName(path): self = .reservedName(path: path)
        }
    }
}

extension YadoriLinkFFI.PreflightResult {
    init(_ value: YadoriLinkModel.PreflightResult) {
        self.init(resolvedPath: value.resolvedPath, pathExists: value.pathExists, isDirectory: value.isDirectory, entryCount: value.entryCount, ignoredEntryCount: value.ignoredEntryCount, totalSizeBytes: value.totalSizeBytes, scanTruncated: value.scanTruncated, freeSpace: value.freeSpace.map { YadoriLinkFFI.FreeSpace($0) }, issues: value.issues.map { YadoriLinkFFI.PreflightIssue($0) }, requiresAcknowledgement: value.requiresAcknowledgement)
    }
}

extension YadoriLinkFFI.ReceivedTransfer {
    init(_ value: YadoriLinkModel.ReceivedTransfer) {
        self.init(destinationDir: value.destinationDir, filesReceived: value.filesReceived, bytesReceived: value.bytesReceived)
    }
}

extension YadoriLinkFFI.RecentError {
    init(_ value: YadoriLinkModel.RecentError) {
        self.init(category: value.category, at: value.at, context: value.context)
    }
}

extension YadoriLinkFFI.ReplicaCopy {
    init(_ value: YadoriLinkModel.ReplicaCopy) {
        self.init(deviceId: value.deviceId, reachability: YadoriLinkFFI.PeerReachability(value.reachability), route: YadoriLinkFFI.RouteKind(value.route))
    }
}

extension YadoriLinkFFI.RevokeEdgeOutcome {
    init(_ value: YadoriLinkModel.RevokeEdgeOutcome) {
        switch value {
        case let .revoked(outcome): self = .revoked(outcome: YadoriLinkFFI.MembershipOutcome(outcome))
        case .alreadyRevoked: self = .alreadyRevoked
        }
    }
}

extension YadoriLinkFFI.RouteKind {
    init(_ value: YadoriLinkModel.RouteKind) {
        switch value {
        case .direct: self = .direct
        case .relay: self = .relay
        case .unknown: self = .unknown
        }
    }
}

extension YadoriLinkFFI.SentTransfer {
    init(_ value: YadoriLinkModel.SentTransfer) {
        self.init(transferId: value.transferId, filesOffered: value.filesOffered, totalSize: value.totalSize)
    }
}

extension YadoriLinkFFI.ShareEdgeState {
    init(_ value: YadoriLinkModel.ShareEdgeState) {
        switch value {
        case .active: self = .active
        case .pendingApproval: self = .pendingApproval
        case let .other(raw): self = .other(raw: raw)
        }
    }
}

extension YadoriLinkFFI.ShareRole {
    init(_ value: YadoriLinkModel.ShareRole) {
        switch value {
        case .owner: self = .owner
        case .editor: self = .editor
        case .viewer: self = .viewer
        case let .other(raw): self = .other(raw: raw)
        }
    }
}

extension YadoriLinkFFI.ShareSummary {
    init(_ value: YadoriLinkModel.ShareSummary) {
        self.init(edgeId: value.edgeId, groupId: value.groupId, groupName: value.groupName, deviceId: value.deviceId, state: YadoriLinkFFI.ShareEdgeState(value.state), role: value.role.map { YadoriLinkFFI.ShareRole($0) })
    }
}

extension YadoriLinkFFI.SignInState {
    init(_ value: YadoriLinkModel.SignInState) {
        switch value {
        case .signedOut: self = .signedOut
        case .signedIn: self = .signedIn
        case let .credentialStoreUnusable(message): self = .credentialStoreUnusable(message: message)
        }
    }
}

extension YadoriLinkFFI.SignOutKind {
    init(_ value: YadoriLinkModel.SignOutKind) {
        switch value {
        case let .revoked(grantsRevoked): self = .revoked(grantsRevoked: grantsRevoked)
        case .alreadyRevoked: self = .alreadyRevoked
        case .confirmedRevokedAfterRejection: self = .confirmedRevokedAfterRejection
        }
    }
}

extension YadoriLinkFFI.SignOutOutcome {
    init(_ value: YadoriLinkModel.SignOutOutcome) {
        self.init(kind: YadoriLinkFFI.SignOutKind(value.kind))
    }
}

extension YadoriLinkFFI.StatusSnapshot {
    init(_ value: YadoriLinkModel.StatusSnapshot) {
        self.init(capturedAt: value.capturedAt, overall: YadoriLinkFFI.OverallState(value.overall), attentionReasons: value.attentionReasons.map { YadoriLinkFFI.AttentionReason($0) }, thisDeviceId: value.thisDeviceId, folders: value.folders.map { YadoriLinkFFI.FolderSummary($0) }, peers: value.peers.map { YadoriLinkFFI.PeerSummary($0) }, transfers: value.transfers.map { YadoriLinkFFI.TransferSummary($0) }, bandwidth: YadoriLinkFFI.BandwidthStatus(value.bandwidth), volumes: value.volumes.map { YadoriLinkFFI.VolumeSummary($0) }, storage: YadoriLinkFFI.StorageSummary(value.storage), update: YadoriLinkFFI.UpdateBadge(value.update), recentErrors: value.recentErrors.map { YadoriLinkFFI.RecentError($0) })
    }
}

extension YadoriLinkFFI.StatusUpdate {
    init(_ value: YadoriLinkModel.StatusUpdate) {
        switch value {
        case let .snapshot(snapshot): self = .snapshot(snapshot: YadoriLinkFFI.StatusSnapshot(snapshot))
        case let .unavailable(error): self = .unavailable(error: YadoriLinkFFI.DesktopError(error))
        }
    }
}

extension YadoriLinkFFI.StorageModeOutcome {
    init(_ value: YadoriLinkModel.StorageModeOutcome) {
        self.init(changed: value.changed, handoff: value.handoff.map { YadoriLinkFFI.HandoffSummary($0) })
    }
}

extension YadoriLinkFFI.StorageSummary {
    init(_ value: YadoriLinkModel.StorageSummary) {
        self.init(blockStoreTotalBytes: value.blockStoreTotalBytes, blockCount: value.blockCount, lastGcAt: value.lastGcAt, reclaimableEstimateBytes: value.reclaimableEstimateBytes)
    }
}

extension YadoriLinkFFI.TransferSummary {
    init(_ value: YadoriLinkModel.TransferSummary) {
        self.init(groupId: value.groupId, folderLocalPath: value.folderLocalPath, path: value.path, bytesDone: value.bytesDone, bytesTotal: value.bytesTotal, blocksDone: value.blocksDone, blocksTotal: value.blocksTotal, sourceDeviceId: value.sourceDeviceId, startedAt: value.startedAt)
    }
}

extension YadoriLinkFFI.TrashedFile {
    init(_ value: YadoriLinkModel.TrashedFile) {
        self.init(localPath: value.localPath, path: value.path, versionSeq: value.versionSeq, lastKnownSize: value.lastKnownSize, originDeviceId: value.originDeviceId, deletedAt: value.deletedAt, kind: YadoriLinkFFI.EntryKind(value.kind), deletedByOperation: value.deletedByOperation)
    }
}

extension YadoriLinkFFI.UnlinkOutcome {
    init(_ value: YadoriLinkModel.UnlinkOutcome) {
        self.init(handoff: value.handoff.map { YadoriLinkFFI.HandoffSummary($0) })
    }
}

extension YadoriLinkFFI.UnreachableCategory {
    init(_ value: YadoriLinkModel.UnreachableCategory) {
        switch value {
        case .noCandidates: self = .noCandidates
        case .noResponse: self = .noResponse
        case .udpBlocked: self = .udpBlocked
        case .handshakeRefused: self = .handshakeRefused
        }
    }
}

extension YadoriLinkFFI.UpdateBadge {
    init(_ value: YadoriLinkModel.UpdateBadge) {
        self.init(state: YadoriLinkFFI.UpdateState(value.state), availableVersion: value.availableVersion, mandatory: value.mandatory, waitingForSafePoint: value.waitingForSafePoint, lastErrorCategory: value.lastErrorCategory, channel: value.channel, installSource: value.installSource, holdbackReason: value.holdbackReason)
    }
}

extension YadoriLinkFFI.UpdateConfig {
    init(_ value: YadoriLinkModel.UpdateConfig) {
        self.init(automaticChecks: value.automaticChecks, installMode: YadoriLinkFFI.UpdateInstallMode(value.installMode))
    }
}

extension YadoriLinkFFI.UpdateInstallMode {
    init(_ value: YadoriLinkModel.UpdateInstallMode) {
        switch value {
        case .automatic: self = .automatic
        case .manual: self = .manual
        case let .other(raw): self = .other(raw: raw)
        }
    }
}

extension YadoriLinkFFI.UpdateInstallOutcome {
    init(_ value: YadoriLinkModel.UpdateInstallOutcome) {
        switch value {
        case .installing: self = .installing
        case .deferred: self = .deferred
        case let .storeManaged(guidance): self = .storeManaged(guidance: guidance)
        case let .other(raw): self = .other(raw: raw)
        }
    }
}

extension YadoriLinkFFI.UpdateState {
    init(_ value: YadoriLinkModel.UpdateState) {
        switch value {
        case .idle: self = .idle
        case .checking: self = .checking
        case .available: self = .available
        case .heldBack: self = .heldBack
        case .killSwitched: self = .killSwitched
        case .downloading: self = .downloading
        case .downloaded: self = .downloaded
        case .verified: self = .verified
        case .installing: self = .installing
        case .failed: self = .failed
        case .deferred: self = .deferred
        case .upToDate: self = .upToDate
        case let .unknown(raw): self = .unknown(raw: raw)
        }
    }
}

extension YadoriLinkFFI.UpdateStatus {
    init(_ value: YadoriLinkModel.UpdateStatus) {
        self.init(currentVersion: value.currentVersion, channel: value.channel, installSource: value.installSource, lastCheckedAt: value.lastCheckedAt, state: YadoriLinkFFI.UpdateState(value.state), availableVersion: value.availableVersion, releaseNotesUrl: value.releaseNotesUrl, mandatory: value.mandatory, holdbackReason: value.holdbackReason, waitingForSafePoint: value.waitingForSafePoint, lastErrorCategory: value.lastErrorCategory, lastErrorMessage: value.lastErrorMessage, config: YadoriLinkFFI.UpdateConfig(value.config))
    }
}

extension YadoriLinkFFI.VolumeSummary {
    init(_ value: YadoriLinkModel.VolumeSummary) {
        self.init(path: value.path, state: YadoriLinkFFI.FreeSpaceState(value.state), availableBytes: value.availableBytes, headroomBytes: value.headroomBytes)
    }
}
