#!/bin/bash
#
# Builds the Swift binding of the client layer for the macOS app.
#
#  1. `yadorilink-apple-ffi` as a static library (release, aarch64-apple-darwin),
#     copied to shell-ext/macos/YadoriLinkApp/FFI/lib/ (not checked in).
#  2. The Swift sources and C headers UniFFI generates from that library, into
#     shell-ext/macos/YadoriLinkApp/FFI/Generated/ (checked in, so the Xcode
#     project and reviews see them), plus the module map the two headers
#     need.
#  3. The app's field-for-field mapping between the binding and the Swift
#     mirror types (check-swift-mirror.py --emit-mapping), and the mirror drift
#     check (scripts/check-swift-mirror.py).
#
# Usage:
#   scripts/generate-swift-bindings.sh           build and regenerate
#   scripts/generate-swift-bindings.sh --check   build, then fail if anything
#                                                checked in differs from what
#                                                the current Rust code generates
#
# The Xcode project runs this before compiling the YadoriLinkFFI framework, so
# an app build always links the library its Swift was generated from: the
# generated code refuses to load a library whose API checksums differ.

set -euo pipefail

# Under Xcode, start over in a clean environment. Xcode exports hundreds of
# build settings (linker variables such as LD_DEPENDENCY_INFO_FILE and
# LD_EXPORT_SYMBOLS among them) that are meant for its own compiler and
# linker invocations; cargo's linker picks them up and produces host
# proc-macro libraries dyld refuses to load. The PATH is a terminal's, so
# `cc` is the xcrun shim that finds the SDK on its own. protoc is resolved
# from the caller's PATH first: ipc-proto's build script needs it, and CI
# installs it outside that fixed PATH.
if [ -n "${XCODE_VERSION_ACTUAL:-}" ] && [ -z "${YADORILINK_CLEAN_ENV:-}" ]; then
    PROTOC_BIN="${PROTOC:-$(command -v protoc || true)}"
    exec env -i YADORILINK_CLEAN_ENV=1 HOME="$HOME" USER="${USER:-}" \
        PATH="$HOME/.cargo/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin:/usr/local/bin" \
        TMPDIR="${TMPDIR:-/tmp}" \
        ${PROTOC_BIN:+PROTOC="$PROTOC_BIN"} \
        ${CARGO_TARGET_DIR:+CARGO_TARGET_DIR="$CARGO_TARGET_DIR"} \
        ${CARGO_HOME:+CARGO_HOME="$CARGO_HOME"} \
        ${RUSTUP_HOME:+RUSTUP_HOME="$RUSTUP_HOME"} \
        /bin/bash "$0" "$@"
fi

CHECK=0
if [ "${1:-}" = "--check" ]; then
    CHECK=1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
FFI_DIR="$REPO_ROOT/shell-ext/macos/YadoriLinkApp/FFI"
GENERATED_DIR="$FFI_DIR/Generated"
MAPPING_FILE="$REPO_ROOT/shell-ext/macos/YadoriLinkApp/App/Live/FFIMapping.swift"
TARGET="aarch64-apple-darwin"

# Xcode runs build scripts with a minimal PATH.
export PATH="$HOME/.cargo/bin:/opt/homebrew/bin:/usr/local/bin:$PATH"

cd "$REPO_ROOT"

# Wherever this machine's cargo puts build output (an environment variable or
# a `.cargo/config.toml` override may move it).
TARGET_DIR="$(cargo metadata --format-version 1 --no-deps \
    | python3 -c 'import json, sys; print(json.load(sys.stdin)["target_directory"])')"

echo "== building yadorilink-apple-ffi ($TARGET, release) =="
cargo build -p yadorilink-apple-ffi --release --target "$TARGET"
echo "== building the Swift binding generator =="
cargo build -p yadorilink-apple-ffi --features bindgen --bin uniffi-bindgen-swift

LIBRARY="$TARGET_DIR/$TARGET/release/libyadorilink_apple_ffi.a"
BINDGEN="$TARGET_DIR/debug/uniffi-bindgen-swift"
test -f "$LIBRARY" || { echo "missing $LIBRARY"; exit 1; }

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

"$BINDGEN" --swift-sources --headers "$LIBRARY" "$WORK/raw"

mkdir -p "$WORK/Generated/include"
cp "$WORK/raw/"*.swift "$WORK/Generated/"
cp "$WORK/raw/"*.h "$WORK/Generated/include/"
# One clang module per generated header, named the way each generated Swift
# file imports it. UniFFI's own module map would put both headers in a single
# module named after the library, which neither Swift file imports.
{
    echo "// Generated by scripts/generate-swift-bindings.sh. Do not edit."
    for header in "$WORK/Generated/include/"*.h; do
        name="$(basename "$header" .h)"
        printf 'module %s {\n    header "%s.h"\n    export *\n}\n' "$name" "$name"
    done
} > "$WORK/Generated/include/module.modulemap"

python3 "$SCRIPT_DIR/check-swift-mirror.py" --emit-mapping "$WORK/Generated" > "$WORK/FFIMapping.swift"

if [ "$CHECK" = "1" ]; then
    status=0
    diff -ru "$GENERATED_DIR" "$WORK/Generated" || status=1
    diff -u "$MAPPING_FILE" "$WORK/FFIMapping.swift" || status=1
    if [ "$status" != "0" ]; then
        echo "The checked-in Swift binding is stale; run scripts/generate-swift-bindings.sh."
        exit 1
    fi
else
    rm -rf "$GENERATED_DIR"
    mkdir -p "$FFI_DIR"
    cp -R "$WORK/Generated" "$GENERATED_DIR"
    cp "$WORK/FFIMapping.swift" "$MAPPING_FILE"
fi

mkdir -p "$FFI_DIR/lib"
cp "$LIBRARY" "$FFI_DIR/lib/libyadorilink_apple_ffi.a"

python3 "$SCRIPT_DIR/check-swift-mirror.py" "$GENERATED_DIR"
echo "== Swift binding up to date: $GENERATED_DIR =="
